import "dotenv/config";
import { GoogleGenerativeAI } from "@google/generative-ai";
const apiKey = process.env.GEMINI_API_KEY;
const genAI = new GoogleGenerativeAI(apiKey);

  
  const model = genAI.getGenerativeModel({
    model: "gemini-2.0-flash-exp",
    systemInstruction: "Add a lot of meaningful emogies to replies , even when using index of points use emogies and also in points rather than dots have some emogies and have less comments in the code that you give me .",
  });
  
  const generationConfig = {
    temperature: 1,
    topP: 0.95,
    topK: 40,
    maxOutputTokens: 8192,
    responseMimeType: "text/plain",
  };
  
   export const geminiAiModel = model.startChat({
      generationConfig,
      history: [
        {
          role: "user",
          parts: [
            {text: "Tell me about dead internet theory\n"},
          ],
        },
        {
          role: "model",
          parts: [
            {text: "Okay, let's dive into the Dead Internet Theory! 💀🌐 This is a fascinating and somewhat unsettling concept, so buckle up! 🚀\n\nThe Dead Internet Theory, in a nutshell, posits that a significant portion of the internet is no longer populated by authentic human beings. Instead, it's largely filled with bots and AI-generated content. 🤖\n\nHere's a breakdown of the main ideas:\n\n*   **The Premise:** 🧐 The core idea is that around 2016 or so, the internet reached a tipping point where automated content creation and manipulation became so prevalent that it became difficult (or impossible) to distinguish genuine human activity from machine-generated activity. ⚙️\n\n*   **The Argument:** 🗣️ Proponents argue that a lot of what we see online – news articles, social media posts, product reviews, forum discussions – is actually generated by sophisticated algorithms designed to manipulate public opinion, sell products, or simply fill the void. 🛒\n\n*   **Evidence (Real or Perceived):** 🤔 Believers point to things like:\n\n    *   **AI-generated content:** 🤖 The increasing sophistication of AI writing tools like GPT-3 and image generators that can produce content indistinguishable from human work. 🎨\n    *   **Bot activity:** 👾 The documented prevalence of bots on social media platforms, used to spread propaganda, manipulate trends, or inflate engagement metrics. 📈\n    *   **Generic content:** 😴 The sheer volume of bland, repetitive, and unoriginal content across the web. 🥱\n    *   **Erosion of online communities:** 🏚️ The perceived decline of genuine, organic online communities in favor of algorithmically driven echo chambers. 📢\n    *   **Content farms:** 🏭 Websites that churn out low-quality articles designed to rank high in search results. 🚜\n\n*   **The \"Why\":** ❓The theory suggests several potential motivations for this:\n\n    *   **Market manipulation:** 💰 Companies using bots and fake reviews to boost sales and damage competitors. ⚔️\n    *   **Political propaganda:** 🗳️ Governments or political groups using bots to spread disinformation and influence public opinion. 📢\n    *   **Data harvesting:** 📡 Companies collecting user data through fake interactions and content. 🕵️‍♀️\n    *   **Simply filling the void:** 🌌 Creating content to populate the internet and make it seem active, even if it's not genuinely human. 🧍➡️🤖\n\n*   **Counterarguments:** ⚔️ Skeptics of the Dead Internet Theory argue:\n\n    *   **Confirmation bias:** 🙈 People are more likely to notice and remember instances of bot activity or generic content, leading them to overestimate its prevalence. 🧠\n    *   **Exaggeration:** 🤥 The theory overstates the capabilities of AI and the extent of bot activity. 🤖\n    *   **Human activity still exists:** 🧍 While there's undeniably a lot of automated content, genuine human interactions and communities still thrive online. 🧑‍🤝‍🧑\n    *   **It's a conspiracy theory:** 😵‍💫 At its extreme, the theory can veer into conspiratorial thinking, suggesting a deliberate and coordinated effort to control the internet. 🕸️\n\n*   **In conclusion:** 🏁 Whether or not the Dead Internet Theory is entirely accurate, it raises important questions about the authenticity of online interactions, the impact of AI on content creation, and the future of the internet. 🤔 It also underscores the need for critical thinking and media literacy in navigating the online world. 🤓\n\nUltimately, it's up to each individual to decide how much weight to give to the Dead Internet Theory. ⚖️ It's a thought-provoking idea, but it's important to approach it with a healthy dose of skepticism and critical analysis. 🧐\n"},
          ],
        },
      ],
    });
  
  